server:         true
permalink:      /blog/:title/
url:            http://rock506.info
markdown:       rdiscount
pygments:       true
paginate:       6
title:          I'm Rock506
feed:           /atom.xml
author:
    name:       Rock506
    weibo:      http://weibo.com/rock506
description:    rock506's Blog