safe:           false
server:         true
permalink:      /blog/:title/
url:            http://rock506.info
markdown:       rdiscount
pygments:       true
paginate:       3
plugins:        ./_plugins
title:          I'm Rock506
feed:           /atom.xml
author:
    name:       Rock506
    weibo:      http://weibo.com/rock506
    pengyou:    http://www.pengyou.com/rock506
    renren:     http://www.renren.com/243445377/profile
    douban:     http://www.douban.com/people/rock506/
description:    rock506's Blog